# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'Mensaje General'), ('odontograma', 'Envío de Odontograma'), ('cita', 'Información de Cita'), ('urgente', 'Urgente')], default='general', max_length=20, verbose_name='Tipo de Mensaje')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('no_leido', 'No Leído'), ('leido', 'Leído'), ('archivado', 'Archivado')], default='no_leido', max_length=20, verbose_name='Estado')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='mensajes/archivos/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='pacientes.cliente', verbose_name='Cliente Relacionado')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='personal.perfil', verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
