# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicacion', '0001_initial'),
        ('personal', '0001_initial'),
        ('historial_clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='odontograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='historial_clinico.odontograma', verbose_name='Odontograma Adjunto'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='personal.perfil', verbose_name='Remitente'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['-fecha_envio'], name='comunicacio_fecha_e_297747_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['destinatario', 'estado'], name='comunicacio_destina_a5b64b_idx'),
        ),
    ]
