# Generated by Django 5.2.5 on 2025-08-24 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(unique=True)),
                ('paciente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('paciente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paciente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tomada', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('administrativo', 'Administrativo'), ('dentista', 'Dentista')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
