# Generated by Django 5.2.5 on 2025-08-25 00:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha_hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Trabajador', 'verbose_name_plural': 'Perfiles de Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='cita',
            name='tomada',
        ),
        migrations.AddField(
            model_name='cita',
            name='actualizada_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to='citas.perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='citas.perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_consulta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_colegio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato: +999999999. Hasta 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
