# Generated by Django 5.2.5 on 2025-10-06 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cliente_cita_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('materiales', 'Materiales Dentales'), ('instrumentos', 'Instrumentos'), ('medicamentos', 'Medicamentos'), ('equipos', 'Equipos'), ('consumibles', 'Consumibles'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=1)),
                ('unidad_medida', models.CharField(default='unidad', max_length=50)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_creados', to='citas.perfil')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='citas.insumo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.perfil')),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
