# Generated by Django 5.2.5 on 2025-10-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_options_insumo_movimientoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dentista_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'rol': 'dentista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to='citas.perfil', verbose_name='Dentista Asignado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='disponible', max_length=20),
        ),
    ]
