# Generated by Django 5.2.5 on 2025-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cliente_dentista_asignado_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notas_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Paciente'),
        ),
    ]
