# Generated by Django 5.2.5 on 2025-10-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_notas_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('paciente_email', models.EmailField(max_length=254, verbose_name='Email del Paciente')),
                ('paciente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('paciente_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('antecedentes_medicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Médicos')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medicamentos_actuales', models.TextField(blank=True, null=True, verbose_name='Medicamentos Actuales')),
                ('higiene_oral', models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('critica', 'Crítica')], default='buena', max_length=20, verbose_name='Higiene Oral')),
                ('estado_general', models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('critica', 'Crítica')], default='buena', max_length=20, verbose_name='Estado General')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('plan_tratamiento', models.TextField(blank=True, null=True, verbose_name='Plan de Tratamiento')),
                ('proxima_cita', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='citas.perfil')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.PositiveIntegerField(verbose_name='Número del Diente')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('cariado', 'Cariado'), ('obturado', 'Obturado'), ('perdido', 'Perdido'), ('endodoncia', 'Endodoncia'), ('corona', 'Corona'), ('implante', 'Implante'), ('puente', 'Puente'), ('protesis', 'Prótesis'), ('extraccion', 'Extracción')], default='sano', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Diente')),
                ('fecha_tratamiento', models.DateField(blank=True, null=True, verbose_name='Fecha del Tratamiento')),
                ('costo_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del Tratamiento')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='citas.odontograma')),
            ],
            options={
                'verbose_name': 'Estado de Diente',
                'verbose_name_plural': 'Estados de Dientes',
                'ordering': ['numero_diente'],
                'unique_together': {('odontograma', 'numero_diente')},
            },
        ),
    ]
