# Generated by Django 5.2.5 on 2025-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_odontograma_estadodiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puede_crear_odontogramas',
            field=models.BooleanField(default=True, verbose_name='Puede crear odontogramas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_gestionar_citas',
            field=models.BooleanField(default=True, verbose_name='Puede gestionar citas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_gestionar_clientes',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar clientes'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_gestionar_insumos',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar insumos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_gestionar_personal',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar personal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='puede_ver_reportes',
            field=models.BooleanField(default=False, verbose_name='Puede ver reportes'),
        ),
    ]
