# Generated by Django 5.2.5 on 2025-10-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_create_all_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField(verbose_name='Cantidad Utilizada')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_odontogramas', to='citas.insumo')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='citas.odontograma')),
            ],
            options={
                'verbose_name': 'Insumo Utilizado en Odontograma',
                'verbose_name_plural': 'Insumos Utilizados en Odontogramas',
                'ordering': ['-fecha_uso'],
            },
        ),
    ]
