# Generated by Django 5.2.5 on 2025-10-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0020_add_imagen_to_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('estrellas', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('comentario', models.TextField(help_text='Mensaje de feedback del cliente (máximo 500 caracteres)', max_length=500, verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('revisada', 'Revisada'), ('archivada', 'Archivada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT/NIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('correo_enviado', models.BooleanField(default=False, verbose_name='Correo Enviado')),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío del Correo')),
            ],
            options={
                'verbose_name': 'Solicitud de Insumo',
                'verbose_name_plural': 'Solicitudes de Insumos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='citas_mensa_fecha_e_051886_idx',
            old_name='citas_mensa_fecha_e_d0e5f5_idx',
        ),
        migrations.RenameIndex(
            model_name='mensaje',
            new_name='citas_mensa_destina_c9ef61_idx',
            old_name='citas_mensa_destina_a34c9a_idx',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='cita',
            name='notas_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor_texto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor (Texto Legacy)'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to='citas.perfil'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_consulta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='citas.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_revisadas', to='citas.perfil', verbose_name='Revisada Por'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to='citas.perfil'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_principales', to='citas.proveedor', verbose_name='Proveedor Principal'),
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='citas.insumo'),
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='citas.proveedor'),
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to='citas.perfil'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['-fecha_creacion'], name='citas_evalu_fecha_c_6ed631_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estado'], name='citas_evalu_estado_a95820_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estrellas'], name='citas_evalu_estrell_b7b28f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('cliente',)},
        ),
    ]
