# Generated by Django 5.2.5 on 2025-10-27 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0021_evaluacion_proveedor_solicitudinsumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(default='Clínica Dental', max_length=200, verbose_name='Nombre de la Clínica')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato: +999999999. Hasta 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato: +999999999. Hasta 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Secundario')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Alternativo')),
                ('horario_atencion', models.TextField(default='Lunes a Viernes: 9:00 - 18:00\nSábados: 9:00 - 13:00', verbose_name='Horario de Atención')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_info_clinica', to='citas.perfil', verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Información de la Clínica',
                'verbose_name_plural': 'Información de la Clínica',
            },
        ),
    ]
