# Generated by Django 5.2.5 on 2025-10-28 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0023_perfil_foto_perfil_requiere_acceso_sistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Rol Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('puede_ver_citas', models.BooleanField(default=True, verbose_name='Ver Citas')),
                ('puede_crear_citas', models.BooleanField(default=True, verbose_name='Crear Citas')),
                ('puede_editar_citas', models.BooleanField(default=False, verbose_name='Editar Citas')),
                ('puede_eliminar_citas', models.BooleanField(default=False, verbose_name='Eliminar Citas')),
                ('puede_ver_todas_citas', models.BooleanField(default=False, verbose_name='Ver Todas las Citas')),
                ('puede_ver_clientes', models.BooleanField(default=True, verbose_name='Ver Clientes')),
                ('puede_crear_clientes', models.BooleanField(default=False, verbose_name='Crear Clientes')),
                ('puede_editar_clientes', models.BooleanField(default=False, verbose_name='Editar Clientes')),
                ('puede_eliminar_clientes', models.BooleanField(default=False, verbose_name='Eliminar Clientes')),
                ('puede_asignar_pacientes', models.BooleanField(default=False, verbose_name='Asignar Pacientes a Dentistas')),
                ('puede_ver_odontogramas', models.BooleanField(default=True, verbose_name='Ver Odontogramas')),
                ('puede_crear_odontogramas', models.BooleanField(default=True, verbose_name='Crear Odontogramas')),
                ('puede_editar_odontogramas', models.BooleanField(default=False, verbose_name='Editar Odontogramas')),
                ('puede_eliminar_odontogramas', models.BooleanField(default=False, verbose_name='Eliminar Odontogramas')),
                ('puede_ver_personal', models.BooleanField(default=False, verbose_name='Ver Personal')),
                ('puede_crear_personal', models.BooleanField(default=False, verbose_name='Crear Personal')),
                ('puede_editar_personal', models.BooleanField(default=False, verbose_name='Editar Personal')),
                ('puede_eliminar_personal', models.BooleanField(default=False, verbose_name='Eliminar Personal')),
                ('puede_gestionar_permisos', models.BooleanField(default=False, verbose_name='Gestionar Permisos de Personal')),
                ('puede_ver_insumos', models.BooleanField(default=False, verbose_name='Ver Insumos')),
                ('puede_crear_insumos', models.BooleanField(default=False, verbose_name='Crear Insumos')),
                ('puede_editar_insumos', models.BooleanField(default=False, verbose_name='Editar Insumos')),
                ('puede_eliminar_insumos', models.BooleanField(default=False, verbose_name='Eliminar Insumos')),
                ('puede_gestionar_stock', models.BooleanField(default=False, verbose_name='Gestionar Stock')),
                ('puede_ver_proveedores', models.BooleanField(default=False, verbose_name='Ver Proveedores')),
                ('puede_crear_proveedores', models.BooleanField(default=False, verbose_name='Crear Proveedores')),
                ('puede_editar_proveedores', models.BooleanField(default=False, verbose_name='Editar Proveedores')),
                ('puede_eliminar_proveedores', models.BooleanField(default=False, verbose_name='Eliminar Proveedores')),
                ('puede_enviar_solicitudes', models.BooleanField(default=False, verbose_name='Enviar Solicitudes a Proveedores')),
                ('puede_ver_dashboard', models.BooleanField(default=True, verbose_name='Ver Dashboard')),
                ('puede_ver_reportes', models.BooleanField(default=False, verbose_name='Ver Reportes')),
                ('puede_exportar_datos', models.BooleanField(default=False, verbose_name='Exportar Datos')),
                ('puede_ver_estadisticas', models.BooleanField(default=False, verbose_name='Ver Estadísticas')),
                ('puede_ver_evaluaciones', models.BooleanField(default=False, verbose_name='Ver Evaluaciones')),
                ('puede_gestionar_evaluaciones', models.BooleanField(default=False, verbose_name='Gestionar Evaluaciones')),
                ('puede_usar_mensajeria', models.BooleanField(default=True, verbose_name='Usar Sistema de Mensajería')),
                ('puede_enviar_mensajes_masivos', models.BooleanField(default=False, verbose_name='Enviar Mensajes Masivos')),
                ('puede_gestionar_roles', models.BooleanField(default=False, verbose_name='Gestionar Roles y Permisos')),
                ('puede_modificar_configuracion', models.BooleanField(default=False, verbose_name='Modificar Configuración del Sistema')),
            ],
            options={
                'verbose_name': 'Rol Personalizado',
                'verbose_name_plural': 'Roles Personalizados',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='citas_rolpe_nombre_9aeef4_idx'), models.Index(fields=['activo'], name='citas_rolpe_activo_c99d2a_idx')],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol_personalizado',
            field=models.ForeignKey(blank=True, help_text='Rol con permisos específicos. Si se asigna, prevalece sobre permisos individuales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_rol', to='citas.rolpersonalizado', verbose_name='Rol Personalizado'),
        ),
    ]
