# Generated by Django 5.2.5 on 2025-10-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0024_rolpersonalizado_perfil_rol_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol_personalizado',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('dentista', 'Dentista'), ('general', 'General (Acceso Completo)')], max_length=20),
        ),
        migrations.DeleteModel(
            name='RolPersonalizado',
        ),
    ]
