# Generated by Django 5.2.5 on 2025-11-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0025_remove_perfil_rol_personalizado_alter_perfil_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_email', models.EmailField(max_length=254, verbose_name='Email del Paciente')),
                ('paciente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('tipo', models.CharField(choices=[('panoramica', 'Panorámica'), ('periapical', 'Periapical'), ('bitewing', 'Bite-wing'), ('oclusal', 'Oclusal'), ('cefalometrica', 'Cefalométrica'), ('tomografia', 'Tomografía'), ('otra', 'Otra')], default='periapical', max_length=20, verbose_name='Tipo de Radiografía')),
                ('imagen', models.ImageField(upload_to='radiografias/%Y/%m/%d/', verbose_name='Imagen de la Radiografía')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_tomada', models.DateField(blank=True, help_text='Fecha en que se tomó la radiografía (si es diferente de la fecha de carga)', null=True, verbose_name='Fecha en que se tomó la radiografía')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='radiografias_subidas', to='citas.perfil', verbose_name='Dentista')),
            ],
            options={
                'verbose_name': 'Radiografía',
                'verbose_name_plural': 'Radiografías',
                'ordering': ['-fecha_carga'],
                'indexes': [models.Index(fields=['paciente_email'], name='citas_radio_pacient_0da21b_idx'), models.Index(fields=['-fecha_carga'], name='citas_radio_fecha_c_61d633_idx'), models.Index(fields=['dentista'], name='citas_radio_dentist_294d03_idx')],
            },
        ),
    ]
