# Generated by Django 5.2.5 on 2025-11-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0026_radiografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas', to='citas.cliente', verbose_name='Cliente del Sistema'),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiografias', to='citas.cliente', verbose_name='Cliente del Sistema'),
        ),
    ]
