# Generated by Django 5.2.5 on 2025-11-03 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0027_odontograma_cliente_radiografia_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final cobrado (puede diferir del precio base del servicio)', max_digits=10, null=True, verbose_name='Precio Cobrado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_consulta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Consulta (Texto Libre)'),
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('preventivo', 'Preventivo'), ('restaurador', 'Restaurador'), ('endodoncico', 'Endodóncico'), ('protesico', 'Protésico'), ('quirurgico', 'Quirúrgico'), ('estetico', 'Estético'), ('ortodontico', 'Ortodóncico'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('activo', models.BooleanField(default=True, verbose_name='Servicio Activo')),
                ('requiere_dentista', models.BooleanField(default=True, help_text='Si este servicio requiere un dentista específico', verbose_name='Requiere Dentista')),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración estimada en minutos', null=True, verbose_name='Duración Estimada')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to='citas.perfil', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
