# Generated by Django 4.2.7 on 2025-11-06 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0028_cita_precio_cobrado_alter_cita_tipo_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinsumo',
            name='monto_egreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto del Egreso'),
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='registrar_como_egreso',
            field=models.BooleanField(default=False, verbose_name='Registrar como Egreso en Finanzas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Solo números celulares chilenos. Formato: +56912345678', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser un celular chileno en formato: +56912345678 (solo números celulares)', regex='^\\+569\\d{8}$')]),
        ),
    ]
