# Generated by Django 4.2.7 on 2025-11-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0030_ingresomanual_egresomanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiografia',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita en la que se tomó esta radiografía (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiografias', to='citas.cita', verbose_name='Cita Asociada'),
        ),
        migrations.AddField(
            model_name='radiografia',
            name='imagen_anotada',
            field=models.ImageField(blank=True, help_text='Imagen con las anotaciones guardadas (se genera automáticamente)', null=True, upload_to='radiografias/anotadas/%Y/%m/%d/', verbose_name='Imagen con Anotaciones'),
        ),
    ]
