# Generated by Django 4.2.7 on 2025-11-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0031_agregar_cita_y_anotaciones_a_radiografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita en la que se creó esta ficha odontológica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas', to='citas.cita', verbose_name='Cita Asociada'),
        ),
    ]
