# Generated by Django 4.2.7 on 2025-11-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('citas', '0033_agregar_campos_cliente_rut_fecha_alergias'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Horario Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='personal.perfil', verbose_name='Dentista')),
            ],
            options={
                'verbose_name': 'Horario de Dentista',
                'verbose_name_plural': 'Horarios de Dentistas',
                'ordering': ['dentista', 'dia_semana', 'hora_inicio'],
                'unique_together': {('dentista', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.RemoveField(
            model_name='egresomanual',
            name='creado_por',
        ),
        migrations.AlterUniqueTogether(
            name='estadodiente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='estadodiente',
            name='odontograma',
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='revisada_por',
        ),
        migrations.RemoveField(
            model_name='informacionclinica',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='ingresomanual',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor_principal',
        ),
        migrations.RemoveField(
            model_name='insumoodontograma',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='insumoodontograma',
            name='odontograma',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='odontograma',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='movimientoinsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='movimientoinsumo',
            name='realizado_por',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='radiografia',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='radiografia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='radiografia',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='solicitado_por',
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='pacientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to='personal.perfil'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='personal.perfil'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to='personal.perfil', verbose_name='Creado por'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='EgresoManual',
        ),
        migrations.DeleteModel(
            name='EstadoDiente',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
        migrations.DeleteModel(
            name='InformacionClinica',
        ),
        migrations.DeleteModel(
            name='IngresoManual',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='InsumoOdontograma',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='MovimientoInsumo',
        ),
        migrations.DeleteModel(
            name='Odontograma',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Radiografia',
        ),
        migrations.DeleteModel(
            name='SolicitudInsumo',
        ),
    ]
