# Generated by Django 4.2.7 on 2025-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0034_horariodentista_remove_egresomanual_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Llegada'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_espera', 'En Espera'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='disponible', max_length=20),
        ),
    ]
