# Generated by Django 4.2.7 on 2025-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0035_agregar_estado_en_espera_y_hora_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_espera', 'En Espera'), ('listo_para_atender', 'Listo para Atender'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No se presentó')], default='disponible', max_length=20),
        ),
    ]
