# Generated by Django 4.2.7 on 2025-11-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('citas', '0036_agregar_estados_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='completada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_completadas', to='personal.perfil', verbose_name='Completada por'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_ajuste_precio',
            field=models.TextField(blank=True, help_text='Justificación si el precio difiere del precio base del servicio', null=True, verbose_name='Motivo del Ajuste de Precio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas_finalizacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales al completar la cita', null=True, verbose_name='Notas de Finalización'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_espera', 'En Espera'), ('listo_para_atender', 'Listo para Atender'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No Llegó')], default='disponible', max_length=20),
        ),
    ]
