# Generated by Django 4.2.7 on 2025-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0037_cita_completada_por_cita_fecha_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_no_asistencia',
            field=models.TextField(blank=True, help_text='Razón por la cual el paciente no asistió a la cita', null=True, verbose_name='Motivo de No Asistencia'),
        ),
    ]
