# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('citas', '0038_cita_motivo_no_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fase_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='historial_clinico.fasetratamiento', verbose_name='Fase del Tratamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
    ]
