# Generated by Django 4.2.7 on 2025-11-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('citas', '0039_cita_fase_tratamiento_cita_plan_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('acceso', 'Acceso'), ('exportar', 'Exportar'), ('enviar', 'Enviar'), ('completar', 'Completar'), ('cancelar', 'Cancelar'), ('pago', 'Pago'), ('otro', 'Otro')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('citas', 'Citas'), ('clientes', 'Clientes'), ('personal', 'Personal'), ('inventario', 'Inventario'), ('finanzas', 'Finanzas'), ('documentos', 'Documentos'), ('planes', 'Planes de Tratamiento'), ('servicios', 'Servicios'), ('proveedores', 'Proveedores'), ('sistema', 'Sistema'), ('reportes', 'Reportes'), ('otro', 'Otro')], max_length=20, verbose_name='Módulo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('tipo_objeto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to='personal.perfil', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='citas_audit_fecha_h_8f909c_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='citas_audit_usuario_a30a4e_idx'), models.Index(fields=['modulo', '-fecha_hora'], name='citas_audit_modulo_2c3bab_idx'), models.Index(fields=['accion', '-fecha_hora'], name='citas_audit_accion_f8651a_idx')],
            },
        ),
    ]
