# Generated by Django 4.2.7 on 2025-11-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0040_crear_auditoria_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('acceso_denegado', 'Acceso Denegado'), ('exportar', 'Exportar Datos'), ('importar', 'Importar Datos'), ('cambio_estado', 'Cambio de Estado'), ('otro', 'Otro')], max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='modulo',
            field=models.CharField(choices=[('citas', 'Citas'), ('clientes', 'Clientes'), ('personal', 'Personal'), ('inventario', 'Inventario'), ('proveedores', 'Proveedores'), ('finanzas', 'Finanzas'), ('documentos', 'Documentos'), ('planes_tratamiento', 'Planes de Tratamiento'), ('odontogramas', 'Odontogramas'), ('radiografias', 'Radiografías'), ('servicios', 'Servicios'), ('configuracion', 'Configuración'), ('auditoria', 'Auditoría'), ('sistema', 'Sistema'), ('otro', 'Otro')], max_length=20, verbose_name='Módulo'),
        ),
    ]
