# Generated by Django 4.2.7 on 2025-12-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0041_actualizar_opciones_auditoria'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS citas_horariodentista (
                id BIGSERIAL PRIMARY KEY,
                dia_semana INTEGER NOT NULL,
                hora_inicio TIME NOT NULL,
                hora_fin TIME NOT NULL,
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                creado_el TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                actualizado_el TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                dentista_id BIGINT NOT NULL,
                CONSTRAINT citas_horariodentista_dentista_id_fkey FOREIGN KEY (dentista_id) REFERENCES personal_perfil(id) ON DELETE CASCADE,
                CONSTRAINT citas_horariodentista_dentista_id_dia_semana_hora_inicio_hora_fin_unique UNIQUE (dentista_id, dia_semana, hora_inicio, hora_fin)
            );
            
            CREATE INDEX IF NOT EXISTS citas_horariodentista_dentista_id_idx ON citas_horariodentista(dentista_id);
            CREATE INDEX IF NOT EXISTS citas_horariodentista_dia_semana_idx ON citas_horariodentista(dia_semana);
            CREATE INDEX IF NOT EXISTS citas_horariodentista_activo_idx ON citas_horariodentista(activo);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS citas_horariodentista CASCADE;
            """
        ),
    ]
