# Generated by Django 4.2.7 on 2025-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0042_create_horariodentista_table'),
        ('personal', '0002_alter_perfil_telefono'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Eliminar la foreign key antigua si existe
            DO $$ 
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE constraint_name = 'citas_tiposervicio_creado_por_id_b3723554_fk_citas_perfil_id'
                    AND table_name = 'citas_tiposervicio'
                ) THEN
                    ALTER TABLE citas_tiposervicio 
                    DROP CONSTRAINT citas_tiposervicio_creado_por_id_b3723554_fk_citas_perfil_id;
                END IF;
            END $$;
            
            -- Crear la nueva foreign key apuntando a personal_perfil
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE constraint_name = 'citas_tiposervicio_creado_por_id_fk_personal_perfil_id'
                    AND table_name = 'citas_tiposervicio'
                ) THEN
                    ALTER TABLE citas_tiposervicio 
                    ADD CONSTRAINT citas_tiposervicio_creado_por_id_fk_personal_perfil_id 
                    FOREIGN KEY (creado_por_id) 
                    REFERENCES personal_perfil(id) 
                    ON DELETE SET NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Revertir: eliminar la nueva foreign key
            DO $$ 
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints 
                    WHERE constraint_name = 'citas_tiposervicio_creado_por_id_fk_personal_perfil_id'
                    AND table_name = 'citas_tiposervicio'
                ) THEN
                    ALTER TABLE citas_tiposervicio 
                    DROP CONSTRAINT citas_tiposervicio_creado_por_id_fk_personal_perfil_id;
                END IF;
            END $$;
            """
        ),
    ]
