# Generated by Django 4.2.7 on 2025-12-02 15:02
# Migración para corregir todas las foreign keys que apuntan a citas_perfil
# y cambiarlas para que apunten a personal_perfil
# Esta migración corrige las foreign keys que fueron creadas antes de que 
# el modelo Perfil se moviera de citas a personal

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0043_fix_tiposervicio_creado_por_fk'),
        ('personal', '0002_alter_perfil_telefono'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Corregir todas las foreign keys que apuntan a citas_perfil
            -- Esta migración corrige las foreign keys que fueron creadas antes
            -- de que el modelo Perfil se moviera de citas a personal
            
            DO $$ 
            DECLARE
                fk_record RECORD;
                new_constraint_name TEXT;
            BEGIN
                -- Iterar sobre todas las foreign keys que apuntan a citas_perfil
                FOR fk_record IN
                    SELECT 
                        tc.table_name,
                        tc.constraint_name,
                        kcu.column_name
                    FROM information_schema.table_constraints AS tc
                    JOIN information_schema.key_column_usage AS kcu
                        ON tc.constraint_name = kcu.constraint_name
                    JOIN information_schema.constraint_column_usage AS ccu
                        ON ccu.constraint_name = tc.constraint_name
                    WHERE tc.constraint_type = 'FOREIGN KEY'
                        AND ccu.table_name = 'citas_perfil'
                LOOP
                    -- Eliminar la constraint antigua
                    EXECUTE format('ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I', 
                        fk_record.table_name, fk_record.constraint_name);
                    
                    -- Crear nueva constraint apuntando a personal_perfil
                    new_constraint_name := replace(fk_record.constraint_name, 'citas_perfil', 'personal_perfil');
                    
                    EXECUTE format('
                        ALTER TABLE %I 
                        ADD CONSTRAINT %I
                        FOREIGN KEY (%I) 
                        REFERENCES personal_perfil(id) 
                        ON DELETE SET NULL
                    ', fk_record.table_name, new_constraint_name, fk_record.column_name);
                END LOOP;
            END $$;
            """,
            reverse_sql="""
            -- Revertir: esto es complejo, mejor dejar vacío
            -- En caso de necesitar revertir, se debería hacer manualmente
            """
        ),
    ]
