# Generated by Django 5.2.5 on 2025-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='whatsapp_message_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='actualizada_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='creada_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
