# Generated by Django 5.2.5 on 2025-09-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        # El modelo Cita está marcado como managed = False
        # Las modificaciones a la tabla citas_cita deben hacerse en gestion_clinica
    ]
