# Generated by Django 5.2.5 on 2025-10-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cita_whatsapp_message_sid_alter_cita_actualizada_el_and_more'),
    ]

    operations = [
        # El modelo Cita está marcado como managed = False
        # Las modificaciones a la tabla citas_cita deben hacerse en gestion_clinica
    ]
