# Generated by Django 5.2.5 on 2025-10-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cita_whatsapp_message_sid_alter_cita_actualizada_el_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE citas_cita 
                ADD COLUMN IF NOT EXISTS whatsapp_message_sid VARCHAR(100) NULL;
            """,
            reverse_sql="""
                ALTER TABLE citas_cita 
                DROP COLUMN IF EXISTS whatsapp_message_sid;
            """
        ),
    ]
