# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT/NIT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('correo_enviado', models.BooleanField(default=False, verbose_name='Correo Enviado')),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío del Correo')),
                ('registrar_como_egreso', models.BooleanField(default=False, verbose_name='Registrar como Egreso en Finanzas')),
                ('monto_egreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto del Egreso')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='inventario.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='proveedores.proveedor')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Solicitud de Insumo',
                'verbose_name_plural': 'Solicitudes de Insumos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
