# Generated by Django 4.2.7 on 2025-11-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='correo_enviado',
        ),
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='fecha_envio_correo',
        ),
        migrations.RemoveField(
            model_name='solicitudinsumo',
            name='registrar_como_egreso',
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('fecha_entrega_esperada', models.DateField(verbose_name='Fecha de Entrega Esperada')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('correo_enviado', models.BooleanField(default=False, verbose_name='Correo Enviado')),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío del Correo')),
                ('registrar_como_egreso', models.BooleanField(default=False, verbose_name='Registrar como Egreso en Finanzas')),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Total del Pedido')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to='personal.perfil')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='proveedores.proveedor')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recibidos', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.AddField(
            model_name='solicitudinsumo',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='proveedores.pedido', verbose_name='Pedido'),
        ),
    ]
