"""
Django settings for gestion_clinica project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fx%b_n(+fx6m%#wtfl_e#gh-8odgvg##j53zysyp135!l9j+r&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',     # <--- API
    # Apps del proyecto - ordenadas por dependencias
    'pacientes',          # Base: Cliente
    'personal',           # Base: Perfil
    'citas',              # Depende de: pacientes, personal
    'inventario',         # Depende de: personal
    'proveedores',        # Depende de: personal, inventario
    'historial_clinico',  # Depende de: pacientes, personal, citas, inventario
    'finanzas',           # Depende de: personal
    'comunicacion',       # Depende de: personal, pacientes, historial_clinico
    'evaluaciones',      # Depende de: pacientes, personal
    'configuracion',      # Depende de: personal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_clinica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'citas.context_processors.perfil_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_clinica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinica_db',       # Nombre de tu base de datos
        'USER': 'postgres',       # Usuario de PostgreSQL
        'PASSWORD': 'postgres',# Contraseña del usuario
        'HOST': 'localhost',        # O dirección de tu servidor DB
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticación básica
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/panel/'
LOGOUT_REDIRECT_URL = '/login/'

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

# Configuración de archivos multimedia (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/trabajadores/panel/'  # O la ruta que sea tu panel principal
LOGOUT_REDIRECT_URL = '/trabajadores/login/'  # A dónde ir después de cerrar sesión

# Configuraciones CSRF
CSRF_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS
CSRF_COOKIE_HTTPONLY = False

# Configuración de Email
# Configuración para enviar correos reales con Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juaquinedca@gmail.com'
EMAIL_HOST_PASSWORD = 'hkqeqqcfynzvuddq'  # Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'juaquinedca@gmail.com'  # Email remitente por defecto
SERVER_EMAIL = 'juaquinedca@gmail.com'

# NOTA: Para producción, estas credenciales deberían estar en variables de entorno
# Para volver a modo desarrollo (solo consola): EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juaquinedca@gmail.com'
EMAIL_HOST_PASSWORD = 'hkqeqqcfynzvuddq'  # Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'juaquinedca@gmail.com'  # Email remitente por defecto
SERVER_EMAIL = 'juaquinedca@gmail.com'

# NOTA: Para producción, estas credenciales deberían estar en variables de entorno
# Para volver a modo desarrollo (solo consola): EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juaquinedca@gmail.com'
EMAIL_HOST_PASSWORD = 'hkqeqqcfynzvuddq'  # Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'juaquinedca@gmail.com'  # Email remitente por defecto
SERVER_EMAIL = 'juaquinedca@gmail.com'

# NOTA: Para producción, estas credenciales deberían estar en variables de entorno
# Para volver a modo desarrollo (solo consola): EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juaquinedca@gmail.com'
EMAIL_HOST_PASSWORD = 'hkqeqqcfynzvuddq'  # Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'juaquinedca@gmail.com'  # Email remitente por defecto
SERVER_EMAIL = 'juaquinedca@gmail.com'

# NOTA: Para producción, estas credenciales deberían estar en variables de entorno
# Para volver a modo desarrollo (solo consola): EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'juaquinedca@gmail.com'
EMAIL_HOST_PASSWORD = 'hkqeqqcfynzvuddq'  # Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'juaquinedca@gmail.com'  # Email remitente por defecto
SERVER_EMAIL = 'juaquinedca@gmail.com'

# NOTA: Para producción, estas credenciales deberían estar en variables de entorno
# Para volver a modo desarrollo (solo consola): EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'