# Generated by Django 4.2.7 on 2025-11-15 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(blank=True, help_text='RUT en formato: 12345678-9 (opcional pero recomendado)', max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('telefono', models.CharField(help_text='Solo números celulares chilenos. Formato: +56912345678', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser un celular chileno en formato: +56912345678 (solo números celulares)', regex='^\\+569\\d{8}$')])),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True, verbose_name='Fecha de Nacimiento')),
                ('alergias', models.TextField(blank=True, help_text='Lista de alergias conocidas (medicamentos, materiales dentales, anestesia, etc.). MUY IMPORTANTE para la seguridad del paciente.', null=True, verbose_name='Alergias')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('dentista_asignado', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'rol': 'dentista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to='personal.perfil', verbose_name='Dentista Asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
