# Generated by Django 4.2.7 on 2025-12-01 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Ingrese solo los 8 dígitos del celular (ejemplo: 20589344). El sistema agregará automáticamente el 9 y el código de país (+56).', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser un celular chileno. Ingrese solo los 8 dígitos (ejemplo: 20589344). El sistema agregará automáticamente el 9 y el código de país (+56).', regex='^\\+569\\d{8}$')]),
        ),
    ]
