# Generated by Django 4.2.7 on 2025-12-02 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema web asociado a este cliente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_asociado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Web Asociado'),
        ),
    ]
