"""
Django settings for cliente_web project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-28vh&5z1ku08x3e@gwocph(vtcc=k3shq(!6=4@-v1iuw+c)5t')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cuentas',
    'reservas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cuentas.middleware.ClienteActivoMiddleware',  # Verificar que el cliente esté activo en sistema de gestión
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cliente_web.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cliente_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Railway proporciona DATABASE_URL automáticamente, pero también podemos usar variables individuales
import dj_database_url

# Intentar usar DATABASE_URL de Railway primero
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback a variables individuales
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='clinica_db'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Formato de fecha y hora
USE_L10N = True

# Configuración de locales
import locale
try:
    locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')
except:
    try:
        locale.setlocale(locale.LC_TIME, 'Spanish_Spain.1252')
    except:
        pass  # Si no se puede configurar, usar por defecto


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticación
LOGIN_REDIRECT_URL = 'panel_cliente'
LOGOUT_REDIRECT_URL = 'inicio'

# Backends de autenticación personalizados
AUTHENTICATION_BACKENDS = [
    'cuentas.backends.ClienteBackend',  # Backend personalizado que verifica existencia en sistema de gestión
    'django.contrib.auth.backends.ModelBackend',  # Backend estándar como fallback
]

# Archivos media (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de Twilio para SMS y WhatsApp
# ⚠️ IMPORTANTE: Configura estos valores en el archivo .env
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', 'AC7319b0ea75ab89067722861358686b39')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', 'cfa7d326a809fd880175c86e59f6a228')

# Número de teléfono de Twilio para SMS (formato E.164: +1234567890)
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '+15005550006')
TWILIO_FROM_SMS = os.getenv('TWILIO_FROM_SMS', TWILIO_PHONE_NUMBER)

# Número de WhatsApp de Twilio (puede ser sandbox o número de WhatsApp Business)
# Formato: whatsapp:+14155238886 (sandbox) o whatsapp:+1234567890 (número real)
TWILIO_WHATSAPP_NUMBER = os.getenv('TWILIO_WHATSAPP_NUMBER', 'whatsapp:+14155238886')
TWILIO_FROM_WHATSAPP = os.getenv('TWILIO_FROM_WHATSAPP', TWILIO_WHATSAPP_NUMBER)
TWILIO_WHATSAPP_BUSINESS_NUMBER = os.getenv('TWILIO_WHATSAPP_BUSINESS_NUMBER', TWILIO_FROM_WHATSAPP)

# URL de callback para recibir actualizaciones de estado de mensajes (opcional)
TWILIO_STATUS_CALLBACK = os.getenv('TWILIO_STATUS_CALLBACK', None)

# URL base del sitio para construir enlaces en mensajes
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Información de la clínica para personalizar mensajes (opcional, se obtiene del modelo si no se define)
CLINIC_NAME = config('CLINIC_NAME', default='Clínica Dental San Felipe')
CLINIC_ADDRESS = config('CLINIC_ADDRESS', default='')
CLINIC_PHONE = config('CLINIC_PHONE', default='')
CLINIC_EMAIL = config('CLINIC_EMAIL', default='')
CLINIC_WEBSITE = config('CLINIC_WEBSITE', default='')
CLINIC_MAP_URL = config('CLINIC_MAP_URL', default='https://www.google.com/maps/place/Clinica+San+Felipe/@-38.2356192,-72.3361399,17z/data=!3m1!4b1!4m6!3m5!1s0x966b155a8306e093:0x46de06dfbc92e29d!8m2!3d-38.2356192!4d-72.333565!16s%2Fg%2F11sswz76yt?hl=es&entry=ttu')

# Configuración para conectar con el sistema de gestión
GESTION_API_URL = config('GESTION_API_URL', default='http://localhost:8001/api')  # URL del sistema de gestión
GESTION_BASE_URL = config('GESTION_BASE_URL', default='http://localhost:8001')  # URL base del sistema de gestión (para media files)
GESTION_API_TOKEN = config('GESTION_API_TOKEN', default='')  # Token de autenticación para la API

# Configuración de Email
# Email de la clínica para enviar correos
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'miclinicacontacto@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'rlih chbj etez srst')
# Email desde el cual se enviarán los correos (debe ser el mismo que EMAIL_HOST_USER para Gmail)
EMAIL_FROM = os.getenv('EMAIL_FROM', 'miclinicacontacto@gmail.com')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'miclinicacontacto@gmail.com')