"""
Django settings for cliente_web project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-28vh&5z1ku08x3e@gwocph(vtcc=k3shq(!6=4@-v1iuw+c)5t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cuentas',
    'reservas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'cuentas.middleware.ClienteActivoMiddleware',  # Verificar que el cliente esté activo en sistema de gestión
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cliente_web.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cliente_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinica_db',       # Nombre de tu base de datos
        'USER': 'postgres',       # Usuario de PostgreSQL
        'PASSWORD': 'postgres',# Contraseña del usuario
        'HOST': 'localhost',        # O dirección de tu servidor DB
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Formato de fecha y hora
USE_L10N = True

# Configuración de locales
import locale
try:
    locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')
except:
    try:
        locale.setlocale(locale.LC_TIME, 'Spanish_Spain.1252')
    except:
        pass  # Si no se puede configurar, usar por defecto


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'panel_cliente'
LOGOUT_REDIRECT_URL = 'inicio'

# Backends de autenticación personalizados
AUTHENTICATION_BACKENDS = [
    'cuentas.backends.ClienteBackend',  # Backend personalizado que verifica existencia en sistema de gestión
    'django.contrib.auth.backends.ModelBackend',  # Backend estándar como fallback
]

# Archivos estáticos
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Archivos media (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de Twilio
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', 'default')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', 'default')
TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886"  # Mantener para compatibilidad
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '+1234567890')
TWILIO_FROM_SMS = "+15005550006"  # Número de origen para SMS (usar tu número de Twilio)
TWILIO_CONTENT_SID = "HXb5b62575e6e4ff6129ad7c8efe1f983e"
TWILIO_FORCE_BODY = True  # Forzar texto simple (sin plantillas) para pruebas inmediatas

# URL base del sitio para construir enlaces en mensajes
SITE_URL = "http://localhost:8000"

# Datos de la clínica para personalizar mensajes
CLINIC_NAME = "Clínica Dental"
CLINIC_ADDRESS = "Av. Principal 123, Santiago"
CLINIC_PHONE = "+56 2 2345 6789"
CLINIC_MAP_URL = "https://maps.app.goo.gl/X7qXc81STzVDCbA7A"  # Ej: https://maps.app.goo.gl/xxxx
CLINIC_LAT = ""  # Opcional: latitud, ej. -33.4489
CLINIC_LNG = ""  # Opcional: longitud, ej. -70.6693
CLINIC_EMAIL = "contacto@clinicasonrisas.cl"
CLINIC_WEBSITE = "www.clinicasonrisas.cl"

# Configuración para conectar con el sistema de gestión
GESTION_API_URL = "http://localhost:8001/api"  # URL del sistema de gestión
GESTION_BASE_URL = "http://localhost:8001"  # URL base del sistema de gestión (para media files)
GESTION_API_TOKEN = ""  # Token de autenticación para la API

# Configuración de Email (para notificaciones por email y Email-to-SMS)
# Configura estos valores con tu proveedor de email (Gmail, Outlook, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Cambiar según tu proveedor (smtp.gmail.com, smtp.outlook.com, etc.)
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu-email@gmail.com'  # Tu dirección de email
EMAIL_HOST_PASSWORD = 'tu-contraseña-app'  # Contraseña de aplicación (no la contraseña normal)
EMAIL_FROM = 'tu-email@gmail.com'  # Email del remitente (generalmente igual a EMAIL_HOST_USER)

# Nota: Para Gmail, necesitas crear una "Contraseña de aplicación" en:
# https://myaccount.google.com/apppasswords
# Para Outlook, activa SMTP en la configuración de seguridad