# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('estrellas', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', verbose_name='Calificación')),
                ('comentario', models.TextField(help_text='Mensaje de feedback del cliente (máximo 500 caracteres)', max_length=500, verbose_name='Comentario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('revisada', 'Revisada'), ('archivada', 'Archivada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='pacientes.cliente', verbose_name='Cliente')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_revisadas', to='personal.perfil', verbose_name='Revisada Por')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='evaluacione_fecha_c_5e3de1_idx'), models.Index(fields=['estado'], name='evaluacione_estado_e0ab09_idx'), models.Index(fields=['estrellas'], name='evaluacione_estrell_dfda6c_idx')],
                'unique_together': {('cliente',)},
            },
        ),
    ]
