# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('citas', '0038_cita_motivo_no_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.PositiveIntegerField(verbose_name='Número del Diente')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('cariado', 'Cariado'), ('obturado', 'Obturado'), ('perdido', 'Perdido'), ('endodoncia', 'Endodoncia'), ('corona', 'Corona'), ('implante', 'Implante'), ('puente', 'Puente'), ('protesis', 'Prótesis'), ('extraccion', 'Extracción')], default='sano', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Diente')),
                ('fecha_tratamiento', models.DateField(blank=True, null=True, verbose_name='Fecha del Tratamiento')),
                ('costo_tratamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del Tratamiento')),
            ],
            options={
                'verbose_name': 'Estado de Diente',
                'verbose_name_plural': 'Estados de Dientes',
                'ordering': ['numero_diente'],
            },
        ),
        migrations.CreateModel(
            name='FaseTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Fase')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(help_text='Orden de la fase en el plan', verbose_name='Orden')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto de la Fase')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Fase de Tratamiento',
                'verbose_name_plural': 'Fases de Tratamiento',
                'ordering': ['plan', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='InsumoOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.PositiveIntegerField(verbose_name='Cantidad Utilizada')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
            ],
            options={
                'verbose_name': 'Insumo Utilizado en Odontograma',
                'verbose_name_plural': 'Insumos Utilizados en Odontogramas',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('paciente_email', models.EmailField(max_length=254, verbose_name='Email del Paciente')),
                ('paciente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('paciente_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('antecedentes_medicos', models.TextField(blank=True, null=True, verbose_name='Antecedentes Médicos')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medicamentos_actuales', models.TextField(blank=True, null=True, verbose_name='Medicamentos Actuales')),
                ('higiene_oral', models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('critica', 'Crítica')], default='buena', max_length=20, verbose_name='Higiene Oral')),
                ('estado_general', models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('critica', 'Crítica')], default='buena', max_length=20, verbose_name='Estado General')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('plan_tratamiento', models.TextField(blank=True, null=True, verbose_name='Plan de Tratamiento')),
                ('proxima_cita', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Cita')),
                ('cita', models.ForeignKey(blank=True, help_text='Cita en la que se creó esta ficha odontológica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas', to='citas.cita', verbose_name='Cita Asociada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas', to='pacientes.cliente', verbose_name='Cliente del Sistema')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_email', models.EmailField(max_length=254, verbose_name='Email del Paciente')),
                ('paciente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Paciente')),
                ('tipo', models.CharField(choices=[('panoramica', 'Panorámica'), ('periapical', 'Periapical'), ('bitewing', 'Bite-wing'), ('oclusal', 'Oclusal'), ('cefalometrica', 'Cefalométrica'), ('tomografia', 'Tomografía'), ('otra', 'Otra')], default='periapical', max_length=20, verbose_name='Tipo de Radiografía')),
                ('imagen', models.ImageField(upload_to='radiografias/%Y/%m/%d/', verbose_name='Imagen de la Radiografía')),
                ('imagen_anotada', models.ImageField(blank=True, help_text='Imagen con las anotaciones guardadas (se genera automáticamente)', null=True, upload_to='radiografias/anotadas/%Y/%m/%d/', verbose_name='Imagen con Anotaciones')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_tomada', models.DateField(blank=True, help_text='Fecha en que se tomó la radiografía (si es diferente de la fecha de carga)', null=True, verbose_name='Fecha en que se tomó la radiografía')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cita', models.ForeignKey(blank=True, help_text='Cita en la que se tomó esta radiografía (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiografias', to='citas.cita', verbose_name='Cita Asociada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiografias', to='pacientes.cliente', verbose_name='Cliente del Sistema')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='radiografias_subidas', to='personal.perfil', verbose_name='Dentista')),
            ],
            options={
                'verbose_name': 'Radiografía',
                'verbose_name_plural': 'Radiografías',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('objetivo', models.TextField(verbose_name='Objetivo del Tratamiento')),
                ('presupuesto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto Total')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Final')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('aprobado', 'Aprobado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='borrador', max_length=30, verbose_name='Estado')),
                ('fecha_inicio_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Estimada')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('motivo_eliminacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Eliminación')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas solo visibles para el personal administrativo', null=True, verbose_name='Notas Internas')),
                ('notas_paciente', models.TextField(blank=True, help_text='Notas que pueden ser visibles para el paciente', null=True, verbose_name='Notas para el Paciente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='pacientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to='personal.perfil', verbose_name='Creado por')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='personal.perfil', verbose_name='Dentista Asignado')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_eliminados', to='personal.perfil', verbose_name='Eliminado por')),
                ('odontograma_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_tratamiento', to='historial_clinico.odontograma', verbose_name='Odontograma Inicial')),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='ItemTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción del Item')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='historial_clinico.fasetratamiento', verbose_name='Fase')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_tratamiento', to='citas.tiposervicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Item de Tratamiento',
                'verbose_name_plural': 'Items de Tratamiento',
                'ordering': ['fase', 'id'],
            },
        ),
    ]
