# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoodontograma',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_odontogramas', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='insumoodontograma',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='historial_clinico.odontograma'),
        ),
        migrations.AddField(
            model_name='fasetratamiento',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento'),
        ),
        migrations.AddField(
            model_name='estadodiente',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='historial_clinico.odontograma'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['paciente_email'], name='historial_c_pacient_1399d3_idx'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['-fecha_carga'], name='historial_c_fecha_c_7697eb_idx'),
        ),
        migrations.AddIndex(
            model_name='radiografia',
            index=models.Index(fields=['dentista'], name='historial_c_dentist_f2418f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['-creado_el'], name='historial_c_creado__2cabb3_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['estado'], name='historial_c_estado_0ddbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['dentista', 'estado'], name='historial_c_dentist_76b4df_idx'),
        ),
        migrations.AddIndex(
            model_name='plantratamiento',
            index=models.Index(fields=['cliente'], name='historial_c_cliente_dce87b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fasetratamiento',
            unique_together={('plan', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='estadodiente',
            unique_together={('odontograma', 'numero_diente')},
        ),
    ]
