# Generated by Django 4.2.7 on 2025-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantratamiento',
            name='citas_estimadas',
            field=models.PositiveIntegerField(blank=True, help_text='Número estimado de citas que requerirá este tratamiento', null=True, verbose_name='Citas Estimadas'),
        ),
    ]
