# Generated by Django 4.2.7 on 2025-11-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0039_cita_fase_tratamiento_cita_plan_tratamiento'),
        ('personal', '0001_initial'),
        ('historial_clinico', '0003_plantratamiento_citas_estimadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de Pago')),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de transferencia, cheque, o comprobante', max_length=100, null=True, verbose_name='Número de Comprobante')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True, verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('cita', models.ForeignKey(blank=True, help_text='Si el pago está asociado a una cita específica del tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_tratamiento', to='citas.cita', verbose_name='Cita Asociada')),
                ('plan_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to='personal.perfil', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de Tratamiento',
                'verbose_name_plural': 'Pagos de Tratamiento',
                'ordering': ['-fecha_pago', '-fecha_registro'],
                'indexes': [models.Index(fields=['plan_tratamiento', '-fecha_pago'], name='historial_c_plan_tr_616613_idx')],
            },
        ),
    ]
