# Generated by Django 4.2.7 on 2025-11-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('citas', '0039_cita_fase_tratamiento_cita_plan_tratamiento'),
        ('pacientes', '0001_initial'),
        ('historial_clinico', '0004_pagotratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presupuesto', 'Presupuesto/Tratamiento'), ('odontograma', 'Ficha Odontológica'), ('radiografia', 'Radiografía'), ('consentimiento', 'Consentimiento Informado'), ('receta', 'Receta Médica'), ('factura', 'Factura'), ('nota_medica', 'Nota Médica'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/%d/', verbose_name='Archivo PDF')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('enviado_por_correo', models.BooleanField(default=False, verbose_name='Enviado por Correo')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Destinatario')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='citas.cita', verbose_name='Cita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.cliente', verbose_name='Cliente')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_generados', to='personal.perfil', verbose_name='Generado por')),
                ('odontograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='historial_clinico.odontograma', verbose_name='Odontograma')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['cliente', '-fecha_generacion'], name='historial_c_cliente_6a1bfb_idx'), models.Index(fields=['tipo', '-fecha_generacion'], name='historial_c_tipo_bad307_idx'), models.Index(fields=['-fecha_generacion'], name='historial_c_fecha_g_0f61e3_idx')],
            },
        ),
    ]
