# Generated by Django 4.2.7 on 2025-11-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('historial_clinico', '0005_documentocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.cliente', verbose_name='Cliente'),
        ),
    ]
