# Generated by Django 4.2.7 on 2025-11-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0039_cita_fase_tratamiento_cita_plan_tratamiento'),
        ('personal', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('historial_clinico', '0006_alter_documentocliente_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo_procedimiento', models.CharField(choices=[('extraccion', 'Extracción Dental'), ('endodoncia', 'Endodoncia'), ('implante', 'Implante Dental'), ('ortodoncia', 'Ortodoncia'), ('blanqueamiento', 'Blanqueamiento Dental'), ('cirugia', 'Cirugía Oral'), ('protesis', 'Prótesis Dental'), ('periodoncia', 'Periodoncia'), ('restauracion', 'Restauración'), ('limpieza', 'Limpieza Dental'), ('otro', 'Otro Procedimiento')], max_length=30, verbose_name='Tipo de Procedimiento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('contenido', models.TextField(help_text='Texto del consentimiento. Puede usar variables como {nombre_paciente}, {fecha}, {dentista}, etc.', verbose_name='Contenido del Consentimiento')),
                ('riesgos', models.TextField(blank=True, help_text='Lista de riesgos potenciales', null=True, verbose_name='Riesgos del Procedimiento')),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios del procedimiento', null=True, verbose_name='Beneficios Esperados')),
                ('alternativas', models.TextField(blank=True, help_text='Opciones alternativas al paciente', null=True, verbose_name='Alternativas de Tratamiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Plantilla Activa')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_consentimiento_creadas', to='personal.perfil', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Consentimiento',
                'verbose_name_plural': 'Plantillas de Consentimientos',
                'ordering': ['tipo_procedimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Consentimiento')),
                ('tipo_procedimiento', models.CharField(choices=[('extraccion', 'Extracción Dental'), ('endodoncia', 'Endodoncia'), ('implante', 'Implante Dental'), ('ortodoncia', 'Ortodoncia'), ('blanqueamiento', 'Blanqueamiento Dental'), ('cirugia', 'Cirugía Oral'), ('protesis', 'Prótesis Dental'), ('periodoncia', 'Periodoncia'), ('restauracion', 'Restauración'), ('limpieza', 'Limpieza Dental'), ('otro', 'Otro Procedimiento')], max_length=30, verbose_name='Tipo de Procedimiento')),
                ('contenido', models.TextField(help_text='Texto completo del consentimiento', verbose_name='Contenido del Consentimiento')),
                ('riesgos', models.TextField(blank=True, null=True, verbose_name='Riesgos')),
                ('beneficios', models.TextField(blank=True, null=True, verbose_name='Beneficios')),
                ('alternativas', models.TextField(blank=True, null=True, verbose_name='Alternativas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('firma_paciente', models.TextField(blank=True, help_text='Firma digital del paciente (texto o imagen codificada)', null=True, verbose_name='Firma del Paciente')),
                ('nombre_firmante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Firmante')),
                ('rut_firmante', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT del Firmante')),
                ('nombre_testigo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Testigo')),
                ('firma_testigo', models.TextField(blank=True, null=True, verbose_name='Firma del Testigo')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha hasta la cual el consentimiento es válido', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='consentimientos/%Y/%m/%d/', verbose_name='Archivo PDF')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='citas.cita', verbose_name='Cita Asociada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='pacientes.cliente', verbose_name='Cliente')),
                ('dentista', models.ForeignKey(limit_choices_to={'rol': 'dentista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to='personal.perfil', verbose_name='Dentista Responsable')),
                ('explicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_explicados', to='personal.perfil', verbose_name='Explicado por')),
                ('plan_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historial_clinico.plantratamiento', verbose_name='Plan de Tratamiento')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historial_clinico.plantillaconsentimiento', verbose_name='Plantilla Utilizada')),
            ],
            options={
                'verbose_name': 'Consentimiento Informado',
                'verbose_name_plural': 'Consentimientos Informados',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', '-fecha_creacion'], name='historial_c_cliente_a7db3a_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='historial_c_estado_8aada0_idx'), models.Index(fields=['tipo_procedimiento'], name='historial_c_tipo_pr_cbc624_idx'), models.Index(fields=['-fecha_creacion'], name='historial_c_fecha_c_9af09c_idx')],
            },
        ),
    ]
