# Generated by Django 4.2.7 on 2025-11-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('historial_clinico', '0007_plantillaconsentimiento_consentimientoinformado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='cuidados_postoperatorios',
            field=models.TextField(blank=True, help_text='Indicaciones inmediatas post-tratamiento', null=True, verbose_name='Cuidados Postoperatorios'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='declaracion_comprension',
            field=models.BooleanField(default=False, help_text='El paciente declara haber sido informado según Ley 20.584', verbose_name='Paciente Declara Comprensión'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='derecho_revocacion',
            field=models.BooleanField(default=False, help_text='El paciente conoce su derecho a revocar el consentimiento', verbose_name='Conoce Derecho de Revocación'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico y justificación del procedimiento', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Razón médica que justifica el procedimiento', null=True, verbose_name='Justificación del Tratamiento'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='naturaleza_procedimiento',
            field=models.TextField(blank=True, help_text='Descripción clara de qué es el procedimiento', null=True, verbose_name='Naturaleza del Procedimiento'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='objetivos_tratamiento',
            field=models.TextField(blank=True, help_text='Objetivos principales del tratamiento', null=True, verbose_name='Objetivos del Tratamiento'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='pronostico',
            field=models.TextField(blank=True, help_text='Tasa de éxito esperada y necesidad de controles', null=True, verbose_name='Pronóstico'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='registro_superintendencia',
            field=models.CharField(blank=True, help_text='Número de registro del profesional en la Superintendencia de Salud', max_length=50, null=True, verbose_name='Registro Superintendencia de Salud'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='rut_dentista',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Profesional Tratante'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='rut_explicado_por',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT Profesional Informante'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='rut_testigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT del Testigo'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='cuidados_postoperatorios',
            field=models.TextField(blank=True, help_text='Indicaciones inmediatas post-tratamiento', null=True, verbose_name='Cuidados Postoperatorios'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='diagnostico_base',
            field=models.TextField(blank=True, help_text='Texto base para diagnóstico y justificación', null=True, verbose_name='Diagnóstico Base'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='naturaleza_procedimiento',
            field=models.TextField(blank=True, help_text='Descripción del procedimiento', null=True, verbose_name='Naturaleza del Procedimiento'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='objetivos_tratamiento',
            field=models.TextField(blank=True, help_text='Objetivos principales', null=True, verbose_name='Objetivos del Tratamiento'),
        ),
        migrations.AddField(
            model_name='plantillaconsentimiento',
            name='pronostico',
            field=models.TextField(blank=True, help_text='Tasa de éxito esperada y necesidad de controles', null=True, verbose_name='Pronóstico'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='alternativas',
            field=models.TextField(blank=True, help_text='Opciones alternativas, incluyendo exodoncia y consecuencias de no tratar', null=True, verbose_name='Alternativas de Tratamiento'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='beneficios',
            field=models.TextField(blank=True, help_text='Beneficios del procedimiento', null=True, verbose_name='Beneficios Esperados'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='dentista',
            field=models.ForeignKey(limit_choices_to={'rol': 'dentista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to='personal.perfil', verbose_name='Profesional Tratante'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='explicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_explicados', to='personal.perfil', verbose_name='Profesional Informante'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='riesgos',
            field=models.TextField(blank=True, help_text='Lista exhaustiva de riesgos comunes y graves', null=True, verbose_name='Riesgos y Complicaciones'),
        ),
        migrations.AlterField(
            model_name='plantillaconsentimiento',
            name='alternativas',
            field=models.TextField(blank=True, help_text='Opciones alternativas, incluyendo exodoncia y consecuencias de no tratar', null=True, verbose_name='Alternativas de Tratamiento'),
        ),
        migrations.AlterField(
            model_name='plantillaconsentimiento',
            name='riesgos',
            field=models.TextField(blank=True, help_text='Lista exhaustiva de riesgos comunes y graves', null=True, verbose_name='Riesgos y Complicaciones'),
        ),
    ]
