# Generated by Django 4.2.7 on 2025-11-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0008_consentimientoinformado_cuidados_postoperatorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='fecha_expiracion_token',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la cual el token de firma es válido', null=True, verbose_name='Fecha de Expiración del Token'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='token_firma',
            field=models.CharField(blank=True, help_text='Token único para permitir la firma del consentimiento sin autenticación', max_length=64, null=True, unique=True, verbose_name='Token de Firma'),
        ),
    ]
