# Generated by Django 4.2.7 on 2025-11-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0009_consentimientoinformado_fecha_expiracion_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantratamiento',
            name='fecha_aceptacion_presupuesto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación del Presupuesto'),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='presupuesto_aceptado',
            field=models.BooleanField(default=False, help_text='Indica si el paciente ha aceptado el presupuesto', verbose_name='Presupuesto Aceptado'),
        ),
    ]
