# Generated by Django 4.2.7 on 2025-11-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('historial_clinico', '0010_plantratamiento_fecha_aceptacion_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='aceptacion_verbal',
            field=models.BooleanField(default=False, help_text='El paciente aceptó verbalmente después de revisar los documentos', verbose_name='Aceptación Verbal del Paciente'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='firmado_por_recepcion',
            field=models.BooleanField(default=False, help_text='Indica si el consentimiento fue firmado por recepción con aceptación verbal del paciente', verbose_name='Firmado por Recepción'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='recepcionista_firmante',
            field=models.ForeignKey(blank=True, help_text='Recepcionista que firmó el consentimiento en nombre del paciente', limit_choices_to={'rol': 'administrativo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_firmados_recepcion', to='personal.perfil', verbose_name='Recepcionista que Firmó'),
        ),
    ]
