# Generated by Django 4.2.7 on 2025-11-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('historial_clinico', '0011_consentimientoinformado_aceptacion_verbal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='documento_firmado_fisico',
            field=models.FileField(blank=True, help_text='Documento escaneado o fotografiado que demuestra la firma física del paciente (PDF o imagen)', null=True, upload_to='consentimientos/firmados/%Y/%m/%d/', verbose_name='Documento Firmado Físicamente'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='fecha_subida',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se subió el documento firmado', null=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AddField(
            model_name='consentimientoinformado',
            name='subido_por',
            field=models.ForeignKey(blank=True, help_text='Personal que subió el documento firmado físicamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_subidos', to='personal.perfil', verbose_name='Subido por'),
        ),
    ]
