# Generated by Django 5.2.5 on 2025-10-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
            },
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='telefono_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
