# Generated by Django 5.2.5 on 2025-10-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_codigoverificacion_perfilcliente_telefono_verificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoverificacion',
            options={'ordering': ['-creado_el']},
        ),
        migrations.RemoveField(
            model_name='codigoverificacion',
            name='usado',
        ),
        migrations.AddField(
            model_name='codigoverificacion',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
