# Generated by Django 4.2.7 on 2025-11-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_codigoverificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Lista de alergias conocidas (medicamentos, materiales dentales, anestesia, etc.). MUY IMPORTANTE para la seguridad del paciente.', null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT en formato: 12345678-9 (opcional pero recomendado)', max_length=12, null=True, verbose_name='RUT'),
        ),
    ]
