# Generated by Django 4.2.7 on 2025-11-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_manuales_creados', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Ingreso Manual',
                'verbose_name_plural': 'Ingresos Manuales',
                'ordering': ['-fecha', '-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='EgresoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_manuales_creados', to='personal.perfil')),
            ],
            options={
                'verbose_name': 'Egreso Manual',
                'verbose_name_plural': 'Egresos Manuales',
                'ordering': ['-fecha', '-creado_el'],
            },
        ),
    ]
