# Generated by Django 4.2.7 on 2025-11-15 04:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato: +999999999. Hasta 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('administrativo', 'Administrativo'), ('dentista', 'Dentista'), ('general', 'General (Acceso Completo)')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal/', verbose_name='Foto del Personal')),
                ('requiere_acceso_sistema', models.BooleanField(default=True, verbose_name='Requiere Acceso al Sistema')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_colegio', models.CharField(blank=True, max_length=50, null=True)),
                ('puede_gestionar_citas', models.BooleanField(default=True, verbose_name='Puede gestionar citas')),
                ('puede_gestionar_clientes', models.BooleanField(default=False, verbose_name='Puede gestionar clientes')),
                ('puede_gestionar_insumos', models.BooleanField(default=False, verbose_name='Puede gestionar insumos')),
                ('puede_gestionar_personal', models.BooleanField(default=False, verbose_name='Puede gestionar personal')),
                ('puede_ver_reportes', models.BooleanField(default=False, verbose_name='Puede ver reportes')),
                ('puede_crear_odontogramas', models.BooleanField(default=True, verbose_name='Puede crear odontogramas')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Trabajador',
                'verbose_name_plural': 'Perfiles de Trabajadores',
            },
        ),
    ]
