# Generated by Django 4.2.7 on 2025-12-02 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 8 y 15 dígitos.', regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
